### ISSUE TITLE
Optional ES6 support with esprima-fb

### ISSUE THREAD

**Issue by trabus** [thlorenz/redeyed#1]
I'd like to use cardinal.js (through marked-terminal) for outputting ES6 module code examples to the terminal, but the version of esprima that redeyed uses does not support ES6 module syntax like `import` and `export`.

I'd like to add optional support that will determine via a boolean option (something like `{es6: true}`) to use esprima or esprima-fb for ES6 code. I just wanted to get your opinion before I made a PR.

Thanks!

**Comment by thlorenz** [comment]
Sounds like a great idea. We could do a major release and **change the default to esprima-fb** and supply an option to use older esprima version.
However lets only include esprima-fb as an actual dependency and require users to install other esprima if they want to change that default.

As a matter of fact we could allow users point to an alternate esprima object in the config.
Please ask more questions if I'm not being clear.

We can discuss more details as the PR evolves.
