### ISSUE TITLE
npm install tar.unpack error

### ISSUE THREAD

**Issue by Local9** [thlorenz/redeyed#19]
Experiencing issues during install, tar.unpack error, log attached from npm

Am using Windows 7 with nodejs 6.9.1 and npm 3.10.8

[npm-debug.zip](https://github.com/thlorenz/redeyed/files/553157/npm-debug.zip)

**Comment by valera-rozuvan** [comment]
The same here.

```
npm ERR! tar.unpack untar error c:\npmcache\redeyed\1.0.0\package.tgz
```

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "c:\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.0
npm ERR! path c:\dev\tfs_af\ActiveFinancials\Dev\Code\UI\ActiveFinancials\client\node_modules\.staging\redeyed-a7ee57fb\examples\browser\index.html
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall lstat

npm ERR! enoent ENOENT: no such file or directory, lstat 'c:\dev\tfs_af\ActiveFinancials\Dev\Code\UI\ActiveFinancials\client\node_modules\.staging\redeyed-a7ee57fb\examples\browser\index.html'
npm ERR! enoent ENOENT: no such file or directory, lstat 'c:\dev\tfs_af\ActiveFinancials\Dev\Code\UI\ActiveFinancials\client\node_modules\.staging\redeyed-a7ee57fb\examples\browser\index.html'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\dev\tfs_af\ActiveFinancials\Dev\Code\UI\ActiveFinancials\client\npm-debug.log
```

**Comment by valera-rozuvan** [comment]
**marked-terminal** got updated to `1.7.0`, it uses **cardinal** version `1.0.0`, which in turn uses **redeyed** version `1.0.0`.

This is a big issue because latest **gulp-notify** uses **marked-terminal** through other dependencies.

**gulp** is big in the world of JS. So this issue will probably hit many devs who use gulp.

Please fix!

**Comment by Jordan-T** [comment]
quick fix, install the module directly from the github URL :
```
npm i https://github.com/thlorenz/redeyed/tarball/master
```

**Comment by valera-rozuvan** [comment]
@Jordan-T What about if it's a dependency of some dependency? You can't really tell NPM not to get the latest child dependency of a child dependency...

I should have used **npm-shrinkwrap** ...

**Comment by valera-rozuvan** [comment]
A quick fix in my case is to downgrade **gulp-notify** to version `2.0.0`. Or temporarily disable it altogether.

**Comment by Local9** [comment]
@Jordan-T Due to this being a dependency with a tool I use (angular-cli), it has caused issues and they're using the latest version of this package (1.0.0)

Yes the install works from Git but as for NPM itself this fails on extraction. I have tried permissions, clearing cache and even reinstalling various tools. I'm now unable to work on my current projects but gladly there is no rush.

**Comment by thlorenz** [comment]
> npm ERR! tar.unpack untar error c:\npmcache\redeyed\1.0.0\package.tgz

Clearly an npm issue as redeyed 1.0.0 is in the registry.

```
> lver redeyed
1.0.0
```
Please check with them why the tar file is corrupt.
Keeping this issue open until it's resolved, but afaik there is nothing we can do here.

**Comment by thlorenz** [comment]
Seems to be another odd problem as the tarball seems valid.
`npm install cardinal` worked just fine for me. I double checked the tar file though and that works as well:

```
# thlorenz/tmp
> curl https://registry.npmjs.org/redeyed/-/redeyed-1.0.0.tgz | tar x -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14764  100 14764    0     0  39180      0 --:--:-- --:--:-- --:--:-- 39265

# thlorenz/tmp
> ll
total 0
drwxr-xr-x    4 thlorenz  staff   136 Oct 26 09:10 .
drwxr-xr-x+ 134 thlorenz  staff  4556 Oct 26 09:01 ..
drwxr-xr-x    4 thlorenz  staff   136 Oct 26 09:09 node_modules
drwxr-xr-x   12 thlorenz  staff   408 Oct 26 09:10 package

# thlorenz/tmp
> ll package/
total 88
drwxr-xr-x  12 thlorenz  staff   408 Oct 26 09:10 .
drwxr-xr-x   4 thlorenz  staff   136 Oct 26 09:10 ..
-rw-r--r--   1 thlorenz  staff    96 May  2 12:34 .npmignore
-rw-r--r--   1 thlorenz  staff   118 May  2 12:34 .travis.yml
-rw-r--r--   1 thlorenz  staff  1078 May  2 12:34 LICENSE
-rw-r--r--   1 thlorenz  staff  5971 Aug 25 14:30 README.md
-rw-r--r--   1 thlorenz  staff  2801 May  2 12:34 config-es5.js
-rw-r--r--   1 thlorenz  staff  3290 May  2 12:34 config.js
drwxr-xr-x   5 thlorenz  staff   170 Oct 26 09:10 examples
-rw-r--r--   1 thlorenz  staff   768 Aug 25 14:32 package.json
-rw-r--r--   1 thlorenz  staff  8728 Aug 25 14:30 redeyed.js
drwxr-xr-x  19 thlorenz  staff   646 Oct 26 09:10 test
```

So not sure why you guys are having this problem. Maybe clear your npm cache in case you have a bad version in there, see `npm help cache`.

**Comment by ashclarke** [comment]
Had this problem when installing `gulp-notify`. I'm short on time, so running:

```
npm i https://github.com/thlorenz/redeyed/tarball/master`
npm i gulp-notify
```
worked for me, but I appreciate it's not much of a fix for those using CI or things when npm install is required often.

**Comment by ashclarke** [comment]
Interestingly, `npm i https://github.com/thlorenz/redeyed/tarball/master` succeeds, however `npm i https://github.com/thlorenz/redeyed/tarball/v1.0.0` fails.

**Comment by ashclarke** [comment]
New update. We have ESET antivirus. On a colleague's machine, they were getting notified of a "trojan" being deleted for the `v1.0.0` tarball:

![image](https://cloud.githubusercontent.com/assets/963023/19733553/38bb2918-9b9c-11e6-91b3-d742299ef17d.png)

**Comment by thlorenz** [comment]
Probably is .. seems like the ESET thing is reacting to a false positive.

**Comment by thlorenz** [comment]
Closing for reason [stated here](https://github.com/thlorenz/redeyed/issues/18#issuecomment-256398314)

**Comment by Local9** [comment]
Confirmed, ESET, now to speak with sysadmins. This will be fun.
