### ISSUE TITLE
`examples/browser/index.html` is detected as a virus by antivirus software

### ISSUE THREAD

**Issue by philiptzou** [thlorenz/redeyed#20]
This issue is first reported at https://github.com/angular/angular-cli/issues/2902. The file is detected as "HTML/ScrInject.B trojan" by antivirus software.

I checked the file and it seems ok to me. Not sure why we get the false positive error.

**Comment by thlorenz** [comment]
duplicate of https://github.com/thlorenz/redeyed/issues/19
