### ISSUE TITLE
Methods named as keywords are treated as keywords

### ISSUE THREAD

**Issue by domenic** [thlorenz/redeyed#3]
Code like

```js
canceled
    .then(() => console.log("never happens"))
    .catch(e => console.log("never happens"))
    .finally(() => console.log("always happens"));
```

plus a config like

```json
{
    "Keyword": {
        "_default": {
            "_before": "<span style='color: rgb(78, 103, 200)'>",
            "_after": "</span>"
        }
    }
}
```

leads to the `catch` and `finally` being highlighted, which is not correct. In context, those are not keywords, just identifiers :(

**Comment by thlorenz** [comment]
Yeah, the themes only look for token names.
What you'd have to do is to write a custom one (or fix the existing ones) to be a bit smarter and look for the context _around_ the token.

Here is a [cardinal example](https://github.com/thlorenz/cardinal/blob/master/themes/default.js#L30-L39) and here a [more involved one](https://github.com/thlorenz/redeyed/blob/master/examples/replace-log.js) which does a lot of analysis for the `console` identifier [here](https://github.com/thlorenz/redeyed/blob/master/examples/replace-log.js#L50).

**Comment by thlorenz** [comment]
To be clear you'd give it a function an it is called with [an info object](https://github.com/thlorenz/redeyed#inputs) that should give you a way to figure out what you're dealing with.

**Comment by domenic** [comment]
Hmm. I was hoping redeyed would just be smart out of the box :-/.

Do you consider this a bug, or would I need to write a module full of smarter wrappers?

**Comment by thlorenz** [comment]
> do you consider this a bug

No :P since esprima tells redeyed for some reason that your _thing_ is a `catch` Keyword token and thus it behaves as it should in that case.
What surprises me a bit is that the `catch` function is considered a _Keyword_, see [here](https://github.com/thlorenz/redeyed/blob/master/config.js#L35).
So maybe making your config a bit more specific could already help.

> would I need to write a module full of smarter wrappers

Possibly, but you can mix string wrappers with function wrappers. So you'd only need _smart_ ones for the tricky cases.

**Comment by domenic** [comment]
I guess the fundamental issue here is that redeyed operates on the token level, whereas I need a tool that operates on the AST node level. (If you look at the [parsed AST](http://esprima.org/demo/parse.html?code=canceled%0D%0A%20%20%20%20.then(()%20%3D%3E%20console.log(%22never%20happens%22))%0D%0A%20%20%20%20.catch(e%20%3D%3E%20console.log(%22never%20happens%22))%0D%0A%20%20%20%20.finally(()%20%3D%3E%20console.log(%22always%20happens%22))%3B%0D%0A), it is an identifier, not a keyword.)

Anyway, since not a bug, happy to close.
