### ISSUE TITLE
Use pure tokenizer

### ISSUE THREAD

**Issue by ariya** [thlorenz/redeyed#8]
In case the source is not successfully parsed, redeyed should attempt to process it with a pure tokenizer.

This also means redeyed can:

* still understand minor syntax variants not yet supported by the parser (e.g. upcoming ECMA-262 syntax proposal)
* process incomplete input or other slightly invalid source

**Comment by ariya** [comment]
This is the result from my suggestion on PR #7.

**Comment by ariya** [comment]
Note that PR #8 is just the beginning. I plan to continue the investigation so that it's likely possible (if wanted) to use the tokenizer as the first choice in processing the input.

In addition, I want to ensure that the token delegator (see [my old e-mail](https://groups.google.com/forum/#!topic/esprima/rG_je2lBKRk)) can be leveraged to give a premium advantage (beside a minor speed win): processing a large input doesn't require a huge allocated memory for the token array, as each token - including every line and block comment - can be handling _just-in-time_.

**Comment by thlorenz** [comment]
When I implemented redeyed I wasn't aware of a `tokenize` function.
I assume that this is a bit new? Also I'd expect it to be a lot faster than obtaining the AST right?

**Comment by thlorenz** [comment]
As indicated in the inline comments we should make the API consistent and only get the AST if the user explicitly specifies this via an option.

**Comment by ariya** [comment]
According to Esprima ChangeLog, the tokenizer is introduced in version 1.1 (March 2014).

While the pure tokenizer is faster, the speed margin is not very big (unless the input is monstrous). This is because parsing is relatively fast, the bottleneck is always at scanning each input character.

However, a pure tokenizer has an advantage in memory consumption (no construction of a complex syntax tree). The delegate pattern makes it even more attractive since there is no need to collect every token in a giant array first before processing them.
